### ISSUE TITLE
Bad ui setting value

### ISSUE THREAD

**Issue by Harvester62** [lilly1987/AI-WEBUI-scripts-Random#5]
The following warnings are being displayed in the WebUI console at startup:

Warning: Bad ui setting value: customscript/Random.py/txt2img/fix width height direction/value: 0; Default value "none" will be used instead.
Warning: Bad ui setting value: customscript/Random.py/img2img/fix width height direction/value: 0; Default value "none" will be used instead.

Activating the script in fact the item "fix width height direction" has no default options selected (all are unchecked) possibly this being the cause of the warning. You might consider to set it to "none" by default, as the warning suggests.
Regards.

**Comment by lilly1987** [comment]
A problem that occurred because the settings of the old version remained

- Open ui-config.json in text editor

- delete line or edit to "none"
customscript/Random.py/txt2img/fix width height direction/value
customscript/Random.py/img2img/fix width height direction/value
![2022-12-03 20 43 47](https://user-images.githubusercontent.com/20321215/205439334-72afa56f-aea3-4ab4-855c-09341134af77.png)
